# fly.toml app configuration file generated for movieslay-emerald on 2024-12-09T04:05:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movieslay-emerald'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
